//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoberturasFianzas.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RamosModels", Namespace="http://schemas.datacontract.org/2004/07/CoberturasFianzas.Models")]
    [System.SerializableAttribute()]
    public partial class RamosModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductosModels", Namespace="http://schemas.datacontract.org/2004/07/CoberturasFianzas.Models")]
    [System.SerializableAttribute()]
    public partial class ProductosModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRamoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRamo {
            get {
                return this.idRamoField;
            }
            set {
                if ((this.idRamoField.Equals(value) != true)) {
                    this.idRamoField = value;
                    this.RaisePropertyChanged("idRamo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceExamen")]
    public interface IServiceExamen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/BuscarRamos", ReplyAction="http://tempuri.org/IServiceExamen/BuscarRamosResponse")]
        CoberturasFianzas.ServiceReference1.RamosModels[] BuscarRamos(int id, string Descripcion, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/BuscarRamos", ReplyAction="http://tempuri.org/IServiceExamen/BuscarRamosResponse")]
        System.Threading.Tasks.Task<CoberturasFianzas.ServiceReference1.RamosModels[]> BuscarRamosAsync(int id, string Descripcion, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/BuscarProductos", ReplyAction="http://tempuri.org/IServiceExamen/BuscarProductosResponse")]
        CoberturasFianzas.ServiceReference1.ProductosModels[] BuscarProductos(int id, string Descripcion, string Pais, int idRamos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/BuscarProductos", ReplyAction="http://tempuri.org/IServiceExamen/BuscarProductosResponse")]
        System.Threading.Tasks.Task<CoberturasFianzas.ServiceReference1.ProductosModels[]> BuscarProductosAsync(int id, string Descripcion, string Pais, int idRamos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/VerificarUsuario", ReplyAction="http://tempuri.org/IServiceExamen/VerificarUsuarioResponse")]
        string VerificarUsuario(string userName, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExamen/VerificarUsuario", ReplyAction="http://tempuri.org/IServiceExamen/VerificarUsuarioResponse")]
        System.Threading.Tasks.Task<string> VerificarUsuarioAsync(string userName, string psw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExamenChannel : CoberturasFianzas.ServiceReference1.IServiceExamen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExamenClient : System.ServiceModel.ClientBase<CoberturasFianzas.ServiceReference1.IServiceExamen>, CoberturasFianzas.ServiceReference1.IServiceExamen {
        
        public ServiceExamenClient() {
        }
        
        public ServiceExamenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExamenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExamenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExamenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CoberturasFianzas.ServiceReference1.RamosModels[] BuscarRamos(int id, string Descripcion, string Pais) {
            return base.Channel.BuscarRamos(id, Descripcion, Pais);
        }
        
        public System.Threading.Tasks.Task<CoberturasFianzas.ServiceReference1.RamosModels[]> BuscarRamosAsync(int id, string Descripcion, string Pais) {
            return base.Channel.BuscarRamosAsync(id, Descripcion, Pais);
        }
        
        public CoberturasFianzas.ServiceReference1.ProductosModels[] BuscarProductos(int id, string Descripcion, string Pais, int idRamos) {
            return base.Channel.BuscarProductos(id, Descripcion, Pais, idRamos);
        }
        
        public System.Threading.Tasks.Task<CoberturasFianzas.ServiceReference1.ProductosModels[]> BuscarProductosAsync(int id, string Descripcion, string Pais, int idRamos) {
            return base.Channel.BuscarProductosAsync(id, Descripcion, Pais, idRamos);
        }
        
        public string VerificarUsuario(string userName, string psw) {
            return base.Channel.VerificarUsuario(userName, psw);
        }
        
        public System.Threading.Tasks.Task<string> VerificarUsuarioAsync(string userName, string psw) {
            return base.Channel.VerificarUsuarioAsync(userName, psw);
        }
    }
}
